### ISSUE TITLE
Auto Layout

### ISSUE THREAD

**Issue by jyounus** [JellyDevelopment/JDAnimationKit#1]
Hey there,

Thanks for making this open source! It looks pretty awesome! :D

I haven't had a chance to play around with this yet, but I was wondering how well it works with auto layout and constraints? Does it "just work" or would I have to do something special or does it manually animate the constraints if they are set?

J

**Comment by Juanpe** [comment]
Hi @jyounus!

Thanks! we're glad you like it.

This version isn't working with autolayout, we think that it's a wonderful feature to include it in the next version ;)

**Comment by jyounus** [comment]
That would be excellent if this could be included in the next version. Right now, I can't use this in my project. :(

Looking forward to a new future update! :)
